Smart-Meal-Prep/smart-meal-planning

- .gitignore
- front-end/.gitignore
- front-end/package-lock.json
- front-end/package.json
- front-end/public/index.html
- front-end/src/App.js
- front-end/src/index.js
- server/index.js
- server/package-lock.json
- server/package.json
Create the environment for our project. Including initializing the back-end server and the front-end server.
> SM-15: Initialize server

- server/index.js
- server/models/Users.js
- server/models/index.js
- server/test_db.js
Created the user data base using the ORM in the models.py and changed enviroment for connecting to the server in the index.js for sequelize.
> SM-17: Created user db

- server/controllers/Users.js
- server/index.js
- server/package-lock.json
- server/package.json
- server/routes/Users.js
- server/test/registration.test.js
Enable user to register and be added to data base.
> SM-18: User registration 

- server/controllers/Users.js
- server/routes/Users.js
- server/test/login.test.js
- server/test/registration.test.js
Implemented the login endpoint that allow users to login by there email and password
> SM-19-Login

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/assets/info.txt
- front-end/src/component/Dashboard.js
- front-end/src/component/Home.js
- front-end/src/component/info.txt
- front-end/src/index.js
- front-end/src/styles/info.txt
Defined code structure, component routing, and added bootstrap package.
> SM-25: Defined structure, routing and bootstrap

- server/controllers/Users.js
- server/index.js
- server/package-lock.json
- server/package.json
- server/test/login.test.js
Implemented express session to store cookie of a user session whenever a user logins.
> SM-20-User-authentication

- server/controllers/Users.js
- server/routes/Users.js
- server/test/login.test.js
Implemented logout endpoint that destroys the session on logout. Front-end needs to implement logout more.
> SM-24: Logout endpoint that destroys session

- server/models/Inventory.js
- server/models/Users.js
Added inventory table to models
> SM-27-Inventory-table

- server/controllers/Inventory.js
- server/controllers/Users.js
- server/index.js
- server/models/Inventory.js
- server/routes/Inventory.js
- server/test/inventory.test.js
Implemented inventory get and add methods that will get a users inventory and add a ingredient to a users inventory
> SM-28-Inventory-endpoints

- server/controllers/Inventory.js
- server/test/inventory.test.js
Implemented the delete endpoint for the inventory route that will delete a associated ingredient entry from the users profile
> SM-34-Delete-ingredient

- server/controllers/Inventory.js
- server/routes/Inventory.js
- server/test/inventory.test.js
- server/test/login.test.js
- server/test/registration.test.js
Endpoint for updating the amount of a ingredient a user has
> SM-35-Update-amount

- server/controllers/Profile.js
- server/controllers/Users.js
- server/index.js
- server/routes/Profile.js
- server/test/profile.test.js
- server/test/registration.test.js
Wrote the getProfile method which uses a UserId to return the user's profile
Updated userRegistration method in ./controllers/Users.js to also create a User Profile with the newly registered user's id. So whenever a new user is created, their profile is also created with initially empty allergies and preferences lists, and a userid matching the profile to its user. This feature required that I also update the registration test file to test the creation of the user's profile. After the user is successfully created using Users.create, we await the Profile.create operation to ensure that it has finished creating the user's profile before making assertions about the response.
> SM-30-Get-user-profile

- server/controllers/Profile.js
- server/routes/Profile.js
- server/test/inventory.test.js
- server/test/profile.test.js
Created a post method called addAllergy to add an allergy to the user's allergy list in their profile.
- Example input:
{
"UserId": 4,
"id" : 4,
"ingredient": "Kale"
}
To see if it worked, get the same profile you used the method on with this url as a get method: http://localhost:3001/Profile
> SM-36-Adding-allergies

- front-end/.gitignore
- front-end/src/component/Dashboard.js
- front-end/src/component/user/Login.js
- front-end/src/component/user/Register.js
- front-end/src/config/fetch.js
- server/controllers/Users.js
- server/routes/Users.js
- server/test/login.test.js
Created a endpoint to check whether or not a user has logged in.
If the user has logged in the front-end will retrieve there email, username, and password and store it in a array.
> SM-41-Get-user-information

- server/controllers/Profile.js
- server/routes/Profile.js
- server/test/profile.test.js
Created a post method called removeAllergy to remove an allergy from the user's allergy list.
Endpoint: http://localhost:3001/Profile/removeAllergy
> SM-43-Remove-allergy

- server/controllers/Profile.js
- server/routes/Profile.js
- server/test/profile.test.js
Created endpoint to add to and remove from the user's preferences list
> SM-44: Implemented add/remove functionality for preferences list

- front-end/src/App.js
- front-end/src/component/Dashboard.js
- front-end/src/component/user/Profile.js
- front-end/src/config/fetch.js
Changed userInformation from basic variable to a useState to ensure rerendering of components whenever user information is changed. Also lifted the state from child component (Dashboard) to parent component (App) to be able to pass it down as props to every other component. This way from now on whenever we create a new component, all we have to do is define the route in App.js and pass userInformation as props.
Also added the profile component but did not implement it yet
> SM-48: moved userInfomation to App.js as a useState to pass as props

- front-end/src/App.js
- front-end/src/component/Dashboard.js
- front-end/src/component/management/Inventory.js
- front-end/src/component/user/Profile.js
- front-end/src/config/fetch.js
- server/controllers/Inventory.js
- server/routes/Inventory.js
- server/test/inventory.test.js
Connected inventory get method.
> SM-42-Connect-inventory

- front-end/src/App.js
- front-end/src/component/user/Profile.js
- front-end/src/config/fetch.js
- server/controllers/Profile.js
- server/routes/Profile.js
- server/test/profile.test.js
Finished connecting profile endpoint to front end. Implemented a profile component with UI to add and remove from user's allergies and preferences lists.
> SM-46-Connect-profile-endpoint

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/component/management/Inventory.js
- front-end/src/component/user/Profile.js
- front-end/src/config/fetch.js
- front-end/src/config/list.js
Main things to note for this PR: 
- lists.js :
- Created a new config file called lists.js. This file is responsible for generating maps that hold all possible ingredients, categories (breakfast, vegan, etc.), and areas (italian, mexican, etc.). You can have access to these lists from anywhere in the project by simply importing the lists object from the file. 
- Select components:
-  installed a new dependency called react-select which gives us access to a react component called Select. This component serves as a dropdown menu with the added functionality of letting the user type into the input to search from the dropdown menu. This component's only required prop is 'options' which is a list of objects each with a label and a value like so: { label: Vegan, value: vegan }. The label …
> SM-50-Ingredient-validation

- server/models/Recipes.js
> SM-52-Created-recipe-table

- front-end/package-lock.json
- front-end/src/component/management/Inventory.js
- server/controllers/Recipes.js
- server/routes/Recipes.js
- server/test/recipes.test.js
Wrote a method for getting recipes from the db based on user's inventory. 
Endpoint: http://localhost:3001/recipes/getRecipes/:UserId 
notes:
- I used Sequalize.literal to input hardcoded sql queries as strings to querying the database. This allowed for more complicated querying which is exactly what we needed.
- I implemented 3 sql queries, two for returning arrays of ingredients for each recipe (one containing matching ingredients from the user's inventory one containing missing ingredients), and another for ordering the recipes in descending order by how many matching ingredients there are. Keep in mind this method still does return the whole table, but the ordering is what matters.
- implemented a select component in the inventory page (this was just to make adding to the inventory …
> SM-54-Recipe-suggestions

- front-end/package-lock.json
- front-end/package.json
Added dependencies to deploy front-end to gh pages
> SM-61-Added-config-for-deploying

- front-end/package.json
Changed location of deployment
> SM-62-Change-build-location

- front-end/src/App.js
- front-end/src/component/user/Register/Register.js
- front-end/src/styles/Registration.css
- front-end/src/test/registration.test.js
Implemented css styling to registration page, similar to the login page and render based test cases.
> SM-64-Registration-UI

- front-end/src/component/Dashboard/Dashboard.js
- front-end/src/component/Dashboard/NavigationBar.js
- front-end/src/config/fetch.js
Integrated logout endpoint that destroys the user's session data server side and renders the option to sign in conditionally.
> SM-65-Logout

- .gitignore
- server/config/config.js
- server/index.js
- server/models/index.js
- server/package-lock.json
- server/package.json
Set up a .env file instead of using the settings.js file to store our hidden variables
> SM-66-Env-set-up

- server/routes/Inventory.js
Updated the path for inventory in routes
> SM-66-Updated-inventory-path

- front-end/src/config/fetch.js
Conditionally generate URL  endpoint based on prod condition.
> SM-66-Prod-checker

- server/index.js
Added deployed front-end as a origin path to cors in the back-end server
> SM-66-Changed-cors-origin

- server/index.js
Changed server listening port number to reflect the deployed server port
> SM-66-Changed-port-number

- server/index.js
Changed cors origin path to be *
> SM-66-Change-cors-origin

- front-end/src/component/Dashboard/Dashboard.js
- front-end/src/component/user/Login/Login.js
- server/index.js
Patch cors pre-request error not fetching on the prod server do to invalid credentials.
> SM-66-Cors-error-patch

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/component/Dashboard/DashboardFooter.js
- front-end/src/component/DashboardFooter.js
- front-end/src/component/user/Profile/Profile.js
- front-end/src/styles/DashboardFooter.css
- front-end/src/styles/Profile.css
- front-end/src/test/profile.test.js
Responsive profile settings page that will render corresponding data based on button input.
> SM-67-Profile-setting-page

- README.md
Added a detailed Readme file on how to run the project, contributors, and over all details on the project and link to website
> SM-71-Readme

- front-end/src/component/Dashboard/Dashboardbody.js
Added text to the three info boxes on the dashboard view
> SM-73-Added-text-to-dashboard
